# Vérone Monorepo Workspace
# Configuration workspace pour back-office + canaux de vente

packages:
  # Applications (3 apps: back-office, site-internet, linkme)
  - 'apps/*'

  # Packages partagés (configs, UI, business logic)
  - 'packages/*'
  - 'packages/@verone/*'
