export const Constants = {
  public: {
    Enums: {
      affiliate_product_approval_status: [
        'draft',
        'pending_approval',
        'approved',
        'rejected',
      ],
      app_type: ['back-office', 'site-internet', 'linkme'],
      article_type: ['vente_de_marchandises', 'prestations_de_services'],
      availability_type_enum: [
        'normal',
        'preorder',
        'coming_soon',
        'discontinued',
      ],
      bank_provider: ['qonto', 'revolut'],
      client_type: ['particulier', 'professionnel'],
      customer_source_type: ['internal', 'linkme', 'site-internet', 'manual'],
      document_direction: ['inbound', 'outbound'],
      document_status: [
        'draft',
        'sent',
        'received',
        'paid',
        'partially_paid',
        'overdue',
        'cancelled',
        'refunded',
      ],
      document_type: [
        'customer_invoice',
        'customer_credit_note',
        'supplier_invoice',
        'supplier_credit_note',
        'expense',
      ],
      error_severity_enum: ['critical', 'high', 'medium', 'low'],
      error_status_enum: ['open', 'in_progress', 'resolved', 'closed'],
      error_type_enum: [
        'javascript_error',
        'network_error',
        'ui_bug',
        'performance_issue',
        'console_error',
        'data_validation',
        'functional_bug',
      ],
      feed_export_status_type: [
        'pending',
        'processing',
        'completed',
        'failed',
        'cancelled',
      ],
      feed_format_type: ['csv', 'xml', 'json'],
      feed_platform_type: ['google_merchant', 'facebook_meta', 'custom'],
      image_type_enum: [
        'primary',
        'gallery',
        'technical',
        'lifestyle',
        'thumbnail',
      ],
      language_type: ['fr', 'en', 'pt'],
      manual_payment_type: [
        'cash',
        'check',
        'transfer_other',
        'card',
        'compensation',
        'verified_bubble',
      ],
      matching_status: [
        'unmatched',
        'auto_matched',
        'manual_matched',
        'partial_matched',
        'ignored',
      ],
      movement_type: ['IN', 'OUT', 'ADJUST', 'TRANSFER'],
      organisation_type: ['internal', 'supplier', 'customer', 'partner'],
      package_type: ['single', 'pack', 'bulk', 'custom'],
      payment_terms_type: [
        'IMMEDIATE',
        'NET_15',
        'NET_30',
        'NET_45',
        'NET_60',
        'NET_90',
        'CUSTOM',
      ],
      product_status_type: ['active', 'preorder', 'discontinued', 'draft'],
      purchase_order_status: [
        'draft',
        'validated',
        'partially_received',
        'received',
        'cancelled',
      ],
      purchase_type: ['dropshipping', 'stock', 'on_demand'],
      room_type: [
        'salon',
        'salle_a_manger',
        'chambre',
        'bureau',
        'bibliotheque',
        'salon_sejour',
        'cuisine',
        'salle_de_bain',
        'wc',
        'toilettes',
        'hall_entree',
        'couloir',
        'cellier',
        'buanderie',
        'dressing',
        'cave',
        'grenier',
        'garage',
        'terrasse',
        'balcon',
        'jardin',
        'veranda',
        'loggia',
        'cour',
        'patio',
        'salle_de_jeux',
        'salle_de_sport',
        'atelier',
        'mezzanine',
        'sous_sol',
      ],
      sales_order_status: [
        'draft',
        'validated',
        'partially_shipped',
        'shipped',
        'delivered',
        'cancelled',
      ],
      sample_request_status_type: ['pending_approval', 'approved', 'rejected'],
      sample_status_type: [
        'not_required',
        'request_pending',
        'request_approved',
        'ordered',
        'delivered',
        'approved',
        'rejected',
      ],
      schedule_frequency_type: ['manual', 'daily', 'weekly', 'monthly'],
      season_type: ['spring', 'summer', 'autumn', 'winter', 'all_year'],
      sourcing_status_type: [
        'draft',
        'sourcing_validated',
        'ready_for_catalog',
        'archived',
      ],
      stock_reason_code: [
        'sale',
        'transfer_out',
        'damage_transport',
        'damage_handling',
        'damage_storage',
        'theft',
        'loss_unknown',
        'sample_client',
        'sample_showroom',
        'marketing_event',
        'photography',
        'rd_testing',
        'prototype',
        'quality_control',
        'return_supplier',
        'return_customer',
        'warranty_replacement',
        'inventory_correction',
        'write_off',
        'obsolete',
        'purchase_reception',
        'return_from_client',
        'found_inventory',
        'manual_adjustment',
        'cancelled',
      ],
      stock_status_type: ['in_stock', 'out_of_stock', 'coming_soon'],
      supplier_segment_type: [
        'strategic',
        'preferred',
        'approved',
        'commodity',
        'artisan',
        'goods_supplier',
        'service_provider',
        'logistics',
        'government',
      ],
      sync_run_status: [
        'pending',
        'running',
        'completed',
        'partial',
        'failed',
        'cancelled',
      ],
      sync_type: [
        'transactions',
        'client_invoices',
        'attachments',
        'labels',
        'full',
      ],
      test_status_enum: ['pending', 'passed', 'failed', 'warning'],
      transaction_side: ['credit', 'debit'],
      transaction_side_filter: ['debit', 'credit', 'both'],
      user_role_type: [
        'owner',
        'admin',
        'catalog_manager',
        'sales',
        'partner_manager',
        'customer',
      ],
      user_type: ['staff', 'supplier', 'customer', 'partner'],
    },
  },
};
