# KPI: Produits référencés (par fournisseur)
# Nombre de produits catalogués par fournisseur

id: kpi-org-products-per-supplier
name: Produits référencés (par fournisseur)
description: |
  Nombre de produits catalogués pour chaque fournisseur spécifique.
  Métrique importante pour évaluer couverture catalogue par fournisseur.
  Affiché dans cards fournisseur liste ET page détail fournisseur.

module: Organisations
category: Métriques
subcategory: Catalogue
owner: Romeo Dos Santos

formula: |
  products_count = COUNT(products WHERE supplier_id = :supplier_id AND archived_at IS NULL)

  Via relation : supplier._count?.products

inputs:
  - name: supplier_id
    type: uuid
    description: ID du fournisseur
    source: organisations.id WHERE type='supplier'

output:
  type: number
  unit: count
  format: integer
  description: Nombre produits actifs du fournisseur

source:
  table: products
  relation: organisations._count.products (Prisma)
  file: src/app/contacts-organisations/suppliers/page.tsx
  query: |
    SELECT COUNT(*) as products_count
    FROM products
    WHERE supplier_id = :supplier_id
    AND archived_at IS NULL
  calculation_line: 497-502 (liste), variable (détail)

displayed_in:
  - component: src/app/contacts-organisations/suppliers/page.tsx
    location: 'Card fournisseur - Badge produits (ligne ~497-502)'
    description: 'Badge avec icône Package affichant count produits'
    screenshot: suppliers-list-page.png
  - component: src/app/contacts-organisations/suppliers/[supplierId]/page.tsx
    location: 'Section Statistiques - Produits référencés'
    description: 'Statistique détail fournisseur'
    screenshot: supplier-detail-page.png

thresholds:
  excellent: '> 50 produits'
  good: '10-50 produits'
  warning: '1-10 produits'
  critical: '0 produits'
  interpretation: |
    - > 50 : Fournisseur catalogue large
    - 10-50 : Catalogue standard
    - 1-10 : Catalogue limité
    - 0 : Fournisseur sans produits (à nettoyer ou nouveau)

tests:
  - scenario: 'Fournisseur catalogue moyen'
    inputs:
      supplier_id: '9078f112-...'
      products_count: 16
    expected_output: 16
    threshold_expected: 'good'

  - scenario: 'Fournisseur vide'
    inputs:
      supplier_id: 'xxx'
      products_count: 0
    expected_output: 0
    threshold_expected: 'critical'

  - scenario: 'Fournisseur catalogue large'
    inputs:
      supplier_id: 'yyy'
      products_count: 120
    expected_output: 120
    threshold_expected: 'excellent'

metadata:
  created_at: 2025-10-22
  last_updated: 2025-10-22
  validated_by: Romeo Dos Santos
  version: 2.0.0
  status: active
  priority: high

business_notes: |
  **Contexte Vérone** :
  - KPI clé évaluation couverture catalogue
  - Relation products.supplier_id → organisations.id
  - Count via Prisma ._count.products (performance optimisée)

  **Exemples production** (2025-10-22) :
  - Fournisseur 9078f112... : 16 produits
  - Moyenne observée : ~15 produits/fournisseur

  **Action métier** :
  - 0 produits → À compléter ou supprimer fournisseur
  - < 5 produits → Enrichir catalogue fournisseur
  - > 100 produits → Fournisseur stratégique majeur

references:
  - docs/database/SCHEMA-REFERENCE.md (products.supplier_id FK)
  - docs/database/foreign-keys.md (products → organisations)
  - Screenshot: tools/reports/2025-10-22/suppliers-list-page.png
  - Screenshot: tools/reports/2025-10-22/supplier-detail-page.png
