/**
 * API Route: POST /api/emails/linkme-info-request
 * Creates a linkme_info_requests record and sends email with secure form link
 */

import type { NextRequest } from 'next/server';
import { NextResponse } from 'next/server';

import { createClient } from '@supabase/supabase-js';
import { Resend } from 'resend';

import type { Database, Json } from '@verone/types';

import { buildEmailHtml } from '../_shared/email-template';

function getResendClient(): Resend {
  const apiKey = process.env.RESEND_API_KEY;
  if (!apiKey) {
    throw new Error('RESEND_API_KEY environment variable is not set');
  }
  return new Resend(apiKey);
}

function getAdminClient() {
  return createClient<Database>(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.SUPABASE_SERVICE_ROLE_KEY!
  );
}

interface RequestedFieldInfo {
  key: string;
  label: string;
  category: string;
  inputType: string;
}

interface InfoRequestEmailBody {
  salesOrderId: string;
  orderNumber: string;
  recipientEmail: string;
  recipientName: string;
  recipientType: 'requester' | 'owner';
  organisationName: string | null;
  totalTtc: number;
  requestedFields: RequestedFieldInfo[];
  customMessage?: string;
  sentBy: string;
}

const CATEGORY_LABELS: Record<string, string> = {
  responsable: 'Responsable',
  billing: 'Facturation',
  delivery: 'Livraison',
  organisation: 'Entreprise',
};

export async function POST(request: NextRequest) {
  try {
    const body = (await request.json()) as InfoRequestEmailBody;

    const {
      salesOrderId,
      orderNumber,
      recipientEmail,
      recipientName,
      recipientType,
      organisationName,
      totalTtc,
      requestedFields,
      customMessage,
      sentBy,
    } = body;

    if (
      !salesOrderId ||
      !orderNumber ||
      !recipientEmail ||
      !requestedFields?.length ||
      !sentBy
    ) {
      return NextResponse.json(
        { success: false, error: 'Missing required fields' },
        { status: 400 }
      );
    }

    const supabase = getAdminClient();

    // Create info request record (token auto-generated by DB)
    const { data: infoRequest, error: insertError } = await supabase
      .from('linkme_info_requests')
      .insert({
        sales_order_id: salesOrderId,
        requested_fields: requestedFields as unknown as Json,
        custom_message: customMessage ?? null,
        recipient_email: recipientEmail,
        recipient_name: recipientName,
        recipient_type: recipientType,
        sent_by: sentBy,
      })
      .select('id, token')
      .single();

    if (insertError || !infoRequest) {
      console.error('[API Info Request Email] Insert error:', insertError);
      return NextResponse.json(
        { success: false, error: 'Failed to create info request' },
        { status: 500 }
      );
    }

    // Build form URL
    const linkmeUrl =
      process.env.LINKME_PUBLIC_URL ?? 'https://linkme.verone.fr';
    const formUrl = `${linkmeUrl}/complete-info/${infoRequest.token}`;

    // Group fields by category for email
    const fieldsByCategory: Record<string, RequestedFieldInfo[]> = {};
    for (const field of requestedFields) {
      const cat = field.category;
      if (!fieldsByCategory[cat]) fieldsByCategory[cat] = [];
      fieldsByCategory[cat].push(field);
    }

    const fieldsHtml = Object.entries(fieldsByCategory)
      .map(([category, fields]) => {
        const catLabel = CATEGORY_LABELS[category] ?? category;
        const fieldsList = fields
          .map(
            f => `<li style="margin: 4px 0; font-size: 14px;">${f.label}</li>`
          )
          .join('');
        return `
          <div style="margin-bottom: 12px;">
            <p style="margin: 0 0 4px 0; color: #78350f; font-weight: bold; font-size: 13px;">${catLabel}</p>
            <ul style="margin: 0; padding-left: 20px; color: #1f2937;">${fieldsList}</ul>
          </div>`;
      })
      .join('');

    const customMessageHtml = customMessage
      ? `
      <div style="background-color: #ffffff; padding: 16px; border-radius: 6px; margin: 16px 0; border-left: 3px solid #f59e0b;">
        <p style="margin: 0 0 4px 0; color: #78350f; font-weight: bold; font-size: 14px;">Message de notre &eacute;quipe :</p>
        <p style="margin: 0; color: #1f2937; white-space: pre-wrap;">${customMessage}</p>
      </div>`
      : '';

    const formattedTotal = new Intl.NumberFormat('fr-FR', {
      style: 'currency',
      currency: 'EUR',
    }).format(totalTtc);

    const bodyHtml = `
      <p style="margin: 0 0 16px 0;">
        Concernant votre commande <strong>${orderNumber}</strong>${organisationName ? ` pour <strong>${organisationName}</strong>` : ''}
        d&rsquo;un montant de <strong>${formattedTotal}</strong>,
        nous avons besoin d&rsquo;informations compl&eacute;mentaires pour pouvoir la traiter.
      </p>

      <div style="background-color: #fff7ed; padding: 16px; border-radius: 6px; margin: 16px 0; border: 1px solid #fed7aa;">
        <p style="margin: 0 0 8px 0; color: #9a3412; font-weight: bold; font-size: 14px;">Informations manquantes :</p>
        ${fieldsHtml}
      </div>

      ${customMessageHtml}`;

    const emailHtml = buildEmailHtml({
      title: 'Informations compl\u00e9mentaires requises',
      recipientName: recipientName ?? 'Madame, Monsieur',
      accentColor: 'orange',
      bodyHtml,
      ctaUrl: formUrl,
      ctaLabel: 'Compl\u00e9ter les informations',
      footerNote: 'Ce lien est valable 30 jours.',
    });

    const resendClient = getResendClient();
    const { data: emailData, error: emailError } =
      await resendClient.emails.send({
        from: process.env.RESEND_FROM_EMAIL ?? 'commandes@verone.fr',
        to: recipientEmail,
        subject: `Commande ${orderNumber} - Informations compl\u00e9mentaires requises`,
        html: emailHtml,
        replyTo: process.env.RESEND_REPLY_TO ?? 'commandes@verone.fr',
      });

    if (emailError) {
      console.error('[API Info Request Email] Resend error:', emailError);
      return NextResponse.json(
        { success: false, error: emailError.message },
        { status: 500 }
      );
    }

    console.warn(
      `[API Info Request Email] Sent for order ${orderNumber} to ${recipientEmail} (token: ${infoRequest.token})`
    );

    return NextResponse.json({
      success: true,
      emailId: emailData?.id,
      infoRequestId: infoRequest.id,
      token: infoRequest.token,
    });
  } catch (error) {
    console.error('[API Info Request Email] error:', error);
    return NextResponse.json(
      {
        success: false,
        error: error instanceof Error ? error.message : 'Unknown error',
      },
      { status: 500 }
    );
  }
}
