#!/bin/bash
# 🧪 TEST GROUPE 2 - VALIDATION MANUELLE BROWSER
# Généré par: Vérone Debugger
# Date: 2025-10-16

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║  🧪 TEST GROUPE 2 - VALIDATION MANUELLE CONSOLE               ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""

# Vérifier serveur actif
echo "📡 Vérification serveur Next.js..."
if curl -s -o /dev/null -w "%{http_code}" http://localhost:3000 | grep -q "200"; then
    echo "   ✅ Serveur opérationnel sur http://localhost:3000"
else
    echo "   ❌ ERREUR: Serveur non accessible"
    echo "   💡 Relancer: npm run dev"
    exit 1
fi

echo ""
echo "════════════════════════════════════════════════════════════════"
echo "  TEST 2.1 - CATALOGUE FAMILLES"
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "📋 URL: http://localhost:3000/catalogue/families"
echo ""
echo "✅ Actions à effectuer:"
echo "   1. Ouvrir DevTools (Cmd+Option+I)"
echo "   2. Onglet Console"
echo "   3. Vérifier: AUCUNE erreur rouge"
echo "   4. Vérifier: Page affiche liste familles"
echo ""
echo "❌ Erreurs connues à rechercher:"
echo "   - activity_tracking errors"
echo "   - Build/compilation errors"
echo "   - PGRST errors"
echo ""
read -p "▶️  Appuyez sur ENTRÉE pour ouvrir la page..."
open "http://localhost:3000/catalogue/families"

echo ""
echo "════════════════════════════════════════════════════════════════"
echo "  TEST 2.2 - CRÉATION CATÉGORIE (CRITIQUE - Erreur #8)"
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "📋 URL: http://localhost:3000/catalogue/categories"
echo ""
echo "✅ Actions à effectuer:"
echo "   1. Cliquer 'Nouvelle catégorie'"
echo "   2. Nom: test-categorie-validation-2025"
echo "   3. Sélectionner une famille parente"
echo "   4. Cliquer 'Créer'"
echo "   5. Vérifier console: ZERO erreur PGRST204"
echo ""
echo "❌ Erreur CRITIQUE à détecter:"
echo "   PGRST204: Cannot return rows from a mutation that"
echo "   uses primary key in its body without a user"
echo "   specified preference"
echo ""
echo "✅ Succès attendu:"
echo "   - Message 'Catégorie créée avec succès'"
echo "   - Redirection vers page catégorie"
echo "   - Console 100% propre"
echo ""
read -p "▶️  Appuyez sur ENTRÉE pour ouvrir la page..."
open "http://localhost:3000/catalogue/categories"

echo ""
echo "════════════════════════════════════════════════════════════════"
echo "  TEST 2.3 - UPLOAD IMAGE PRODUIT"
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "📋 URL: http://localhost:3000/catalogue/products"
echo ""
echo "✅ Actions à effectuer:"
echo "   1. Sélectionner un produit existant"
echo "   2. Cliquer 'Upload image'"
echo "   3. Sélectionner image locale (.jpg/.png)"
echo "   4. Vérifier upload sans erreur"
echo "   5. Vérifier image affichée"
echo ""
echo "❌ Erreurs à détecter:"
echo "   - Storage errors"
echo "   - CORS errors"
echo "   - RLS policy errors"
echo ""
read -p "▶️  Appuyez sur ENTRÉE pour ouvrir la page..."
open "http://localhost:3000/catalogue/products"

echo ""
echo "════════════════════════════════════════════════════════════════"
echo "  RAPPORT DE TESTS"
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "📝 Pour chaque test, notez:"
echo "   ✅ PASS: 0 erreur console + fonctionnalité OK"
echo "   ❌ FAIL: 1+ erreur console OU fonctionnalité KO"
echo ""
echo "Format rapport:"
echo "   - Test 2.1: [PASS/FAIL] [Description si FAIL]"
echo "   - Test 2.2: [PASS/FAIL] [Description si FAIL]"
echo "   - Test 2.3: [PASS/FAIL] [Description si FAIL]"
echo ""
echo "💾 Sauvegarder screenshots erreurs dans:"
echo "   /Users/romeodossantos/verone-back-office-V1/"
echo ""
echo "🎯 Objectif: 3/3 tests PASS (100% console clean)"
echo ""
