'use client';

import { useToast } from '@verone/common/hooks';
import { createClient } from '@verone/utils/supabase/client';

interface UseSourcingCreateUpdateParams {
  refetch: () => Promise<void>;
}

export function useSourcingCreateUpdate({
  refetch,
}: UseSourcingCreateUpdateParams) {
  const { toast } = useToast();
  const supabase = createClient();

  // Créer un produit en sourcing rapide
  const createSourcingProduct = async (data: {
    name: string;
    supplier_page_url?: string;
    cost_price?: number;
    supplier_reference?: string;
    brand?: string;
    description?: string;
    supplier_moq?: number;
    sourcing_channel?: string;
    supplier_id?: string;
    assigned_client_id?: string;
    enseigne_id?: string;
    imageFiles?: File[];
  }) => {
    try {
      // Validation nom
      if (!data.name?.trim()) {
        toast({
          title: 'Erreur',
          description: 'Le nom du produit est obligatoire',
          variant: 'destructive',
        });
        return null;
      }

      // Déterminer sourcing_type : 'client' si enseigne OU organisation, sinon 'interne'
      const isClientSourcing = !!(data.enseigne_id ?? data.assigned_client_id);

      // Créer le produit (champs facultatifs envoyés uniquement si renseignés)
      const { data: newProduct, error } = await supabase
        .from('products')
        .insert([
          {
            name: data.name,
            supplier_page_url: data.supplier_page_url ?? null,
            cost_price: data.cost_price ?? null,
            supplier_reference: data.supplier_reference ?? null,
            brand: data.brand ?? null,
            description: data.description ?? null,
            supplier_moq: data.supplier_moq ?? null,
            sourcing_channel: data.sourcing_channel ?? null,
            supplier_id: data.supplier_id ?? null,
            assigned_client_id: data.assigned_client_id ?? null,
            enseigne_id: data.enseigne_id ?? null,
            creation_mode: 'sourcing',
            sourcing_type: isClientSourcing ? 'client' : 'interne',
            product_status: 'draft' as const,
            completion_status: 'draft',
            stock_status: 'out_of_stock' as const,
            sku: '', // Required by type, auto-generated by DB trigger
          },
        ])
        .select('id, name, sku, product_status, creation_mode, sourcing_type')
        .single();

      if (error) {
        toast({
          title: 'Erreur',
          description: error.message,
          variant: 'destructive',
        });
        return null;
      }

      // Upload images si fournies (multi)
      if (data.imageFiles && data.imageFiles.length > 0 && newProduct) {
        for (let i = 0; i < data.imageFiles.length; i++) {
          const file = data.imageFiles[i];
          try {
            const fileExt = file.name.split('.').pop();
            const fileName = `${newProduct.id}-${Date.now()}-${i}.${fileExt}`;
            const filePath = `products/${fileName}`;

            const { error: uploadError } = await supabase.storage
              .from('product-images')
              .upload(filePath, file);

            if (uploadError) {
              console.error(`Erreur upload image ${i}:`, uploadError);
              continue;
            }

            const {
              data: { publicUrl },
            } = supabase.storage.from('product-images').getPublicUrl(filePath);

            await supabase.from('product_images').insert([
              {
                product_id: newProduct.id,
                public_url: publicUrl,
                storage_path: filePath,
                is_primary: i === 0,
                image_type: i === 0 ? 'primary' : 'gallery',
              },
            ]);
          } catch (imgError) {
            console.error(`Erreur gestion image ${i}:`, imgError);
          }
        }
      }

      toast({
        title: 'Succès',
        description: 'Produit en sourcing créé',
      });

      await refetch();
      return newProduct;
    } catch (_err) {
      toast({
        title: 'Erreur',
        description: 'Impossible de créer le produit',
        variant: 'destructive',
      });
      return null;
    }
  };

  // Mettre à jour un produit en sourcing
  const updateSourcingProduct = async (
    productId: string,
    data: {
      name?: string;
      supplier_page_url?: string | null;
      cost_price?: number | null;
      eco_tax_default?: number | null;
      supplier_id?: string | null;
      supplier_reference?: string | null;
      margin_percentage?: number | null;
      brand?: string | null;
      description?: string | null;
      supplier_moq?: number | null;
      dimensions?: Record<string, number> | null;
      weight?: number | null;
      internal_notes?: string | null;
    }
  ) => {
    try {
      // Validation basique
      if (
        data.cost_price !== undefined &&
        data.cost_price !== null &&
        data.cost_price <= 0
      ) {
        toast({
          title: 'Erreur',
          description: "Le prix d'achat doit être > 0€",
          variant: 'destructive',
        });
        return false;
      }

      if (data.name !== undefined && !data.name.trim()) {
        toast({
          title: 'Erreur',
          description: 'Le nom du produit ne peut pas être vide',
          variant: 'destructive',
        });
        return false;
      }

      // Construire l'objet de mise à jour avec uniquement les champs fournis
      const updateData: Record<string, unknown> = {};

      if (data.name !== undefined) updateData.name = data.name;
      if (data.supplier_page_url !== undefined)
        updateData.supplier_page_url = data.supplier_page_url;
      if (data.cost_price !== undefined)
        updateData.cost_price = data.cost_price;
      if (data.eco_tax_default !== undefined)
        updateData.eco_tax_default = data.eco_tax_default;
      if (data.margin_percentage !== undefined)
        updateData.margin_percentage = data.margin_percentage;
      if (data.supplier_reference !== undefined)
        updateData.supplier_reference = data.supplier_reference;
      if (data.brand !== undefined) updateData.brand = data.brand;
      if (data.description !== undefined)
        updateData.description = data.description;
      if (data.supplier_moq !== undefined)
        updateData.supplier_moq = data.supplier_moq;
      if (data.dimensions !== undefined)
        updateData.dimensions = data.dimensions;
      if (data.weight !== undefined) updateData.weight = data.weight;
      if (data.internal_notes !== undefined)
        updateData.internal_notes = data.internal_notes;

      // Gérer supplier_id (peut être null pour retirer le fournisseur)
      if (data.supplier_id !== undefined) {
        updateData.supplier_id = data.supplier_id;
      }

      const { error } = await supabase
        .from('products')
        .update(updateData)
        .eq('id', productId);

      if (error) {
        toast({
          title: 'Erreur',
          description: error.message,
          variant: 'destructive',
        });
        return false;
      }

      toast({
        title: 'Succès',
        description: 'Produit mis à jour avec succès',
      });

      await refetch();
      return true;
    } catch (_err) {
      toast({
        title: 'Erreur',
        description: 'Impossible de mettre à jour le produit',
        variant: 'destructive',
      });
      return false;
    }
  };

  return { createSourcingProduct, updateSourcingProduct };
}
